services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db
  chatbot:
    build: ./
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    entrypoint: ["sh", "run.sh"]
volumes:
  mongo_data:
