services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  chatbot:
    build: ./
    env_file:
      - .env
    depends_on:
      - mongo
    entrypoint: ["sh", "run.sh"]
